INSERT INTO usuarios (nombre, apellido, ciudad) VALUES
    ('Juan', 'Pérez', 'Madrid'),
    ('Ana', 'González', 'Barcelona'),
    ('Carlos', 'Martínez', 'Valencia'),
    ('Elena', 'Fernández', 'Sevilla'),
    ('David', 'López', 'Zaragoza'),
    ('Laura', 'Díaz', 'Málaga'),
    ('Javier', 'Gómez', 'Murcia'),
    ('Sara', 'Rodríguez', 'Palma de Mallorca'),
    ('José', 'Hernández', 'Las Palmas'),
    ('María', 'Jiménez', 'Bilbao'),
    ('Miguel', 'Ruiz', 'Alicante'),
    ('Carmen', 'Sánchez', 'Córdoba'),
    ('Pablo', 'Iglesias', 'Valladolid'),
    ('Isabel', 'Torres', 'Vigo'),
    ('Alejandro', 'Santos', 'Gijón'),
    ('Cristina', 'Castro', 'Vitoria'),
    ('Francisco', 'Ortega', 'Granada'),
    ('Raquel', 'Molina', 'Elche'),
    ('Manuel', 'Flores', 'Oviedo'),
    ('Natalia', 'Vega', 'Badalona'),
    ('Rafael', 'Morales', 'Terrassa'),
    ('Victoria', 'Guerrero', 'Cartagena'),
    ('Diego', 'Navarro', 'Jerez de la Frontera'),
    ('Patricia', 'Cano', 'Alcalá de Henares'),
    ('Francisco Javier', 'Mora', 'Fuenlabrada'),
    ('Adriana', 'Reyes', 'San Cristóbal de La Laguna'),
    ('Hugo', 'Fuentes', 'Logroño'),
    ('Martina', 'Gil', 'Santa Coloma de Gramenet'),
    ('Álvaro', 'Pascual', 'Almería'),
    ('Celia', 'Vidal', 'Jaén');
